# Form implementation generated from reading ui file 'windows/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 664)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: qlineargradient(x1:1, y1:1, x2:1, y2:0, stop:0 rgb(30, 30, 30), stop: 0.8 rgb(30, 30, 30), stop:1 rgb(16, 150, 230));\n"
"    font-family: \"Calibri\";\n"
"    font-size: 16pt;\n"
"    color: white;        \n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    font-family: \"Impact\";\n"
"    font-size: 30pt;\n"
"}\n"
"\n"
"QPushButton {\n"
"    padding: 20px;\n"
"    margin: 10px; \n"
"    font-family: \"Arial Black\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#connect_button {\n"
"    background-color: green;\n"
"}\n"
"\n"
"QPushButton#connect_button:hover {\n"
"    background-color: rgb(66, 202, 66);\n"
"}\n"
"\n"
"QPushButton#settings_button {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton#settings_button:hover {\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setTabletTracking(False)
        self.label_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setIndent(0)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.connect_status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.connect_status_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.connect_status_label.setIndent(0)
        self.connect_status_label.setObjectName("connect_status_label")
        self.verticalLayout.addWidget(self.connect_status_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connect_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout.addWidget(self.connect_button)
        self.settings_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout.addWidget(self.settings_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remote Drive Controller"))
        self.title_label.setText(_translate("MainWindow", "Remote Drive Controller"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">Для подключения контроллера необходимо установить на телефон приложение контроллера. После этого в приложении нужно указать IP текущего ПК, а также порт, который должен совпадать с портом подключения в настройках. Для работы аналогового управления неободима установка драйвера VJoy, который можно скачать <a href=\"https://github.com/shauleiz/vJoy/releases\">здесь</a>.</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Статус:"))
        self.connect_status_label.setText(_translate("MainWindow", "Контроллер не подключен"))
        self.connect_button.setText(_translate("MainWindow", "Подключиться"))
        self.settings_button.setText(_translate("MainWindow", "Настройки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
